apiVersion: v1
kind: Service
metadata:
  name: {{ template "ntp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 123
      targetPort: 123
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "ntp.name" . }}
    release: "{{ .Release.Name }}"
